### ISSUE TITLE
server_thread中new 出来的socket_p可能不会被 delete

### ISSUE THREAD

**Issue by DavidLiuXh** [PikaLabs/pink#19]
https://github.com/Qihoo360/pink/blob/fe8cb932b271859f0b7e1a25616f270a90339f1d/pink/src/server_thread.cc#L136

如果这个地方return, 那上面new 出来的socket_p什么时候被 delete?

**Comment by DavidLiuXh** [comment]
Listen不成功还有必要放到server_sockets中吗?

**Comment by gaodq** [comment]
listen不成功一般就是端口冲突了，这时这个server_thread就该被析构了，所以我想new之后直接放server_sockets里等待析构里delete它就行
