### ISSUE TITLE
[Question] Relation with evpp

### ISSUE THREAD

**Issue by diorahman** [PikaLabs/pink#24]
Hi, what's the connection with evpp? And do you think pink can have benefit by adopting libevent too? Thinking of a model like wangle or proxygen that specifically differentiates IO-related and CPU-related pools.

**Comment by gaodq** [comment]
I don't know much about evpp but Pink has no relationship with evpp. Pink is designed to satisfy [Pika](https://github.com/Qihoo360/pika), a nosql database compatible with redis. Thus we have refered redis' design in some respect. In my opinion, libevent is used for cross-platform, Pink doesn't intend to support every platform except Linux. I have read some codes of wangle, brpc and so on, and believe it is really a good idea to differentiate IO-bound and CPU-bound thread pool. We are working on redesigning and this model will be considered.
Thank you.

**Comment by diorahman** [comment]
Cool thanks!
